### ISSUE TITLE
Repeat this configuration checkbox not working for 'Parent' config

### ISSUE THREAD

**Issue by mufapu** [gathercontent/drupal-module#12]
Hi,

When importing the data from gathercontent.com we would like to just configure the top item and then repeat the configuration for all other items.

The 'repeat configuration' checkbox works for most configurable fields (Import as, Text Format, ...) but NOT for the 'Parent' configuration. Parent configuration remains unchanged after checking the box.

This means we would have to configure this manually for each item.

Drupal version used: 7.39
JQuery: 1.10.3

**Comment by Cyapow** [comment]
Updated @mufapu give it a try

**Comment by mufapu** [comment]
Works like a charm. Thanks!
