### ISSUE TITLE
Unable to connect to API: There was a problem contacting the API. Please check your API credentials. Auth Settings

### ISSUE THREAD

**Issue by nasianotta** [gathercontent/drupal-module#13]
Hi team,

I created an API key as per your instructions and tried to connect from Drupal on admin/config/content/gathercontent/login, but I get the error:
"There was a problem contacting the API. Please check your API credentials. Auth Settings"

Can you suggest a way around this?

Thank you.

**Comment by Cyapow** [comment]
Hi @nasianotta 

Could you possibly contact me directly at mat@gathercontent.com and I will be able to help you with your account.

Thanks

Mat
