### ISSUE TITLE
Error message - there was a problem connecting. Please try again later

### ISSUE THREAD

**Issue by susielinubc** [gathercontent/drupal-module#4]
Hi Matt, 

We downloaded the module to try it out. We have a gathercontent account.

1) entered the correct URL and API key under settings
2) successfully connect to be able to see content we can pull to Drupal from gathercontent.
3) after mapping out the fields on admin/config/content/gathercontent/pages_import to click on "import select pages", the following error pops up in the browser 

![screen-shot-2014-05-31-at-2 51](https://cloud.githubusercontent.com/assets/4950745/3140224/46ff5e92-e90e-11e3-8053-1b061f86ae0c.jpg)

Appreciate you pointing us to the right direction.

**Comment by 75th** [comment]
I have this problem, too. It sure is a good thing the admins took the entire conversation offline and then closed the issue, so only three people get the benefit of the solution!

**Comment by 75th** [comment]
Okay, so my version of this issue was caused by one of my text fields allowing multiple (unlimited) values; the GatherContent module didn't account for that possibility, tried to call `$entity->set()` with a string instead of an array, and yielded an EntityMetadataWrapperException. Fortunately, in our case it was a mistake that that field allowed multiple values. But the module should still handle it better.

**Comment by Cyapow** [comment]
@75th sorry the other persons issue was actually caused by permissions problem. So not entirely the same. There is an issue of trying to map fields to incompatible data like you said. If you have a way to handle it I'm more than happy for you to fork off and I can merge it in.

**Comment by gijimmyj** [comment]
@Cyapow can you help me with this as well? I'm having the same issue. I get the same error and then a second error for each file (see the screenshots), and it appears to be related to importing attachments. Could this be a similar permissions issue that you helped  the first user with? 
![error2](https://cloud.githubusercontent.com/assets/2007165/7755588/ce409bbe-ffba-11e4-994b-ce3286f8e98b.png)
![error1](https://cloud.githubusercontent.com/assets/2007165/7755589/ce418f38-ffba-11e4-8f54-162f92d1fda0.png)

**Comment by Cyapow** [comment]
@gijimmyj this sounds like a bug. If the user who's API key it is has access to the page they should be able to download the files. Is it a specific page this happens to or is it for all pages? Did you hit refresh on the importing media page? 

If you like you can email me directly at mat@gathercontent.com and I can take a look for you.

**Comment by onizzzuka** [comment]
I have this error when try to import to field type 'Link'.
Looks like module not understand popular field types that are provided by other modules.
Also, it not understand Metatags - I can't select a field (metatag title, metatag text etc.) where I want to place a content from GatherContent service, just only 'Metatag'.

**Comment by Cyapow** [comment]
Unfortunately these are third party addons which we do not support. You are more than welcome to make the changes needed which I can then merge into the main branch.
