### ISSUE TITLE
Unable to execute import, with alert box saying "Connection error"

### ISSUE THREAD

**Issue by alphex** [gathercontent/drupal-module#7]
The alert box says "There was a problem connecting".   

I've been able to make imports before today, but now I'm receiving this message.

Help!  ;)

Thanks

![2015-05-04 09-36-07](https://cloud.githubusercontent.com/assets/597641/7454373/135551f4-f241-11e4-9613-9013ad2c48e9.jpg)

**Comment by Cyapow** [comment]
Hi Alphex

If you message me directly at support@gathercontent.com I can take a look for you. 99% of the time it is when you are trying to import data to a field that does not support that type of data. But if you email me I can help you find the issue.

Thanks

Mat

**Comment by alphex** [comment]
Emails are sent...  Thank you.
